{% set name = "ultraheatmap" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
<<<<<<< HEAD
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "f025162a483954f32c399a38b6a4ce8dcb7b974438355859518d6e5feff571a6"

build:
  number: 0
=======
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f025162a483954f32c399a38b6a4ce8dcb7b974438355859518d6e5feff571a6

build:
  number: 0
  noarch: python
>>>>>>> 5e4d1751b4c499bd35ccea20a38809d0894f0c6b
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
<<<<<<< HEAD
    - bedtools=2.27.1
    - deeptools=3.0.1
    - gffutils=0.9
    - pybedtools=0.7.10
    - pybigwig=0.3.10
    - pyyaml >= 5.1
=======
    - bedtools >2
    - deeptools >3
    - gffutils
    - pybedtools
    - pybigwig
    - pyyaml >=5.1
>>>>>>> 5e4d1751b4c499bd35ccea20a38809d0894f0c6b

test:
  imports:
    - ultraheatmap

about:
  home: "https://github.com/maxplanck-ie/ultraheatmap/"
<<<<<<< HEAD
  license: "MIT"
  license_family: "MIT"
  summary: "ultraheatmaps facilitates the production of deepTools heatmaps"

extra:
  recipe-maintainers:
    - 'https://github.com/maxplanck-ie/ultraheatmap/'
=======
  license: MIT
  license_family: MIT
  summary: "ultraheatmaps facilitates the production of deepTools heatmaps"
>>>>>>> 5e4d1751b4c499bd35ccea20a38809d0894f0c6b
