{% set version = "1.0" %}

package:
  name: ultraheatmap
  version: {{ version }}

source:
  url: https://github.com/maxplanck-ie/ultraheatmap/archive/{{ version }}.tar.gz
  sha256: 0d815020c44237e30a6614670e20a8ea6476b7b686ac39bc7bb018b1324aaf3a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >3
  run:
    - python >3
    -  bedtools=2.27.1
    - deeptools=3.0.1
    - gffutils=0.9
    - pybedtools=0.7.10
    - pybigwig=0.3.10
    - pyyaml >= 5.1


test:
  imports:
    - ultraheatmaps

about:
  home: 'https://github.com/maxplanck-ie/ultraheatmap/'
  license: GPL3
  summary: ultraheatmaps facilitates the production of deepTools heatmaps.
