package:
  name: krbalancing
  version: 0.0.1dev

source:
  git_url: https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm.git
  git_rev: 1.1.4

build:
  noarch: python
  number: 0
  skip: True

requirements:
  build:
    - python
    - gcc
  run:
    - python
    - eigen >=3.3.7
    - pybind11 >=2.2.4

about:
  home: 'https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm'
  license: GPL3
  summary: This is a c++ extension for python which computes K.R. balanced matrices.
