{% set version = "0.0.2" %}

package:
  name: krbalancing
  version: {{ version }}

source:
  url: https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm/archive/{{ version }}.tar.gz
  sha256: 8efa5f19e4011364b8111052012b29e51d081e4ec86b92229ca02209c6bc023f

build:
  number: 0
  script: '$PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - eigen >=3.3.7
    - pybind11 >=2.2.4
  run:
    - python
    - eigen >=3.3.7
    - pybind11 >=2.2.4
    - llvm-openmp  # [osx]

test:
  imports:
    - krbalancing

about:
  home: 'https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm'
  license: GPL3
  summary: This is a c++ extension for python which computes K.R. balanced matrices.
