package:
  name: krbalancing
  version: 0.0.1

source:
  url: https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm/archive/0.0.1.tar.gz
  sha256: f3cc7e9ae6176ca3ecea3c8a600f1a875821075cf5086c3f1e9da06fde6ee6e0

build:
  noarch: python
  number: 0
  script: '$PYTHON -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv'

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - eigen >=3.3.7
    - pybind11 >=2.2.4
  run:
    - python
    - eigen >=3.3.7
    - pybind11 >=2.2.4

about:
  home: 'https://github.com/deeptools/Knight-Ruiz-Matrix-balancing-algorithm'
  license: GPL3
  summary: This is a c++ extension for python which computes K.R. balanced matrices.
